version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - rabbitmq_python

  producer:
    build: ./producers
    
    container_name: producer_rabbit
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./producers:/usr/src/app
  consumer:
    build: ./consumers
    
    #container_name: consumer_rabbit
    deploy: 
      replicas: 2
    depends_on:
      - rabbitmq
      - producer
    networks:
      - rabbitmq_python
    volumes:
      - ./consumers:/usr/src/app
  producer_temperatura:
    build: ./producers/producers_temperatura

    container_name: producer_temperatura_rabbit
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./producers/producers_temperatura:/usr/src/app
  consumer_temperatura:
    build: ./consumers/consumers_temperatura

    #container_name: consumer_temperatura_rabbit
    deploy: 
      replicas: 2
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./consumers/consumers_temperatura:/usr/src/app
  producer_humedad:
    build: ./producers/producers_humedad

    container_name: producer_humedad_rabbit
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./producers/producers_humedad:/usr/src/app  
  consumer_humedad:
    build: ./consumers/consumers_humedad

    # container_name: consumer_humedad_rabbit
    deploy: 
      replicas: 2
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./consumers/consumers_humedad:/usr/src/app
  producer_posicion:
    build: ./producers/producers_posicion

    container_name: producer_posicion_rabbit
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./producers/producers_posicion:/usr/src/app 
  consumer_posicion:
    build: ./consumers/consumers_posicion

    # container_name: consumer_posicion_rabbit
    deploy: 
      replicas: 2
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./consumers/consumers_posicion:/usr/src/app
  producer_color:
    build: ./producers/producers_color

    container_name: producer_color_rabbit
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./producers/producers_color:/usr/src/app
  consumer_color:
    build: ./consumers/consumers_color

    # container_name: consumer_color_rabbit
    deploy: 
      replicas: 2
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./consumers/consumers_color:/usr/src/app



networks:
  rabbitmq_python:
    driver: bridge
