version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - rabbitmq_python

  producer:
    build: ./producers
    
    container_name: producer_rabbit
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_python
    volumes:
      - ./producers:/usr/src/app
  consumer:
    build: ./consumers
    
    container_name: consumer_rabbit
    depends_on:
      - rabbitmq
      - producer
    networks:
      - rabbitmq_python
    volumes:
      - ./consumers:/usr/src/app

networks:
  rabbitmq_python:
    driver: bridge
