version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  producer:
    build: ./producers
    container_name: producer_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producers:/usr/src/app
   
  consumer:
    build: ./consumers
    #container_name: consumer_kafka
    deploy: 
      replicas: 
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumers:/usr/src/app

    